// lib/core/data/sample_data.dart
import 'package:language_learning_app/models.dart';

class SampleData {
  static const List<LanguageModel> languages = [
    LanguageModel(
      id: 'hindi',
      name: 'Hindi',
      nativeName: 'हिन्दी',
      flagEmoji: '🇮🇳',
      description: 'The most widely spoken language in India',
      totalWords: 1200,
      categories: ['Vocabulary', 'Grammar', 'Phrases', 'Numbers', 'Colors', 'Food', 'Travel', 'Family'],
    ),
    LanguageModel(
      id: 'gujarati',
      name: 'Gujarati',
      nativeName: 'ગુજરાતી',
      flagEmoji: '🏛️',
      description: 'Spoken by 55 million people across Gujarat',
      totalWords: 900,
      categories: ['Vocabulary', 'Grammar', 'Phrases', 'Numbers', 'Colors', 'Food', 'Travel', 'Family'],
    ),
    LanguageModel(
      id: 'marathi',
      name: 'Marathi',
      nativeName: 'मराठी',
      flagEmoji: '🟠',
      description: 'The official language of Maharashtra',
      totalWords: 850,
      categories: ['Vocabulary', 'Grammar', 'Phrases', 'Numbers', 'Colors', 'Food'],
    ),
    LanguageModel(
      id: 'bengali',
      name: 'Bengali',
      nativeName: 'বাংলা',
      flagEmoji: '🌸',
      description: 'Spoken by over 230 million people worldwide',
      totalWords: 800,
      categories: ['Vocabulary', 'Grammar', 'Phrases', 'Numbers', 'Colors', 'Food'],
    ),
    LanguageModel(
      id: 'tamil',
      name: 'Tamil',
      nativeName: 'தமிழ்',
      flagEmoji: '🌺',
      description: 'One of the oldest classical languages in the world',
      totalWords: 750,
      categories: ['Vocabulary', 'Grammar', 'Phrases', 'Numbers', 'Colors', 'Food'],
    ),
    LanguageModel(
      id: 'telugu',
      name: 'Telugu',
      nativeName: 'తెలుగు',
      flagEmoji: '⭐',
      description: 'The most spoken Dravidian language',
      totalWords: 700,
      categories: ['Vocabulary', 'Grammar', 'Phrases', 'Numbers', 'Colors', 'Food'],
    ),
  ];

  static List<WordModel> getHindiWords() {
    return [
      // Vocabulary - Greetings
      WordModel(
        id: 'h001',
        word: 'नमस्ते',
        translation: 'Hello / Greetings',
        transliteration: 'Namaste',
        pronunciation: 'nuh-muh-stay',
        languageId: 'hindi',
        category: 'Vocabulary',
        exampleSentence: 'नमस्ते, आप कैसे हैं?',
        exampleTranslation: 'Hello, how are you?',
        difficulty: 1,
      ),
      WordModel(
        id: 'h002',
        word: 'धन्यवाद',
        translation: 'Thank you',
        transliteration: 'Dhanyavaad',
        pronunciation: 'dhun-yuh-vaad',
        languageId: 'hindi',
        category: 'Vocabulary',
        exampleSentence: 'आपकी मदद के लिए धन्यवाद।',
        exampleTranslation: 'Thank you for your help.',
        difficulty: 1,
      ),
      WordModel(
        id: 'h003',
        word: 'कृपया',
        translation: 'Please',
        transliteration: 'Kripaya',
        pronunciation: 'krip-aa-ya',
        languageId: 'hindi',
        category: 'Phrases',
        exampleSentence: 'कृपया यहाँ आएं।',
        exampleTranslation: 'Please come here.',
        difficulty: 1,
      ),
      WordModel(
        id: 'h004',
        word: 'माफ़ करना',
        translation: 'Sorry / Excuse me',
        transliteration: 'Maaf karna',
        pronunciation: 'maaf kur-naa',
        languageId: 'hindi',
        category: 'Phrases',
        exampleSentence: 'माफ़ करना, मुझे देर हो गई।',
        exampleTranslation: 'Sorry, I am late.',
        difficulty: 1,
      ),
      // Numbers
      WordModel(
        id: 'h005',
        word: 'एक',
        translation: 'One',
        transliteration: 'Ek',
        pronunciation: 'ek',
        languageId: 'hindi',
        category: 'Numbers',
        exampleSentence: 'मुझे एक सेब चाहिए।',
        exampleTranslation: 'I want one apple.',
        difficulty: 1,
      ),
      WordModel(
        id: 'h006',
        word: 'दो',
        translation: 'Two',
        transliteration: 'Do',
        pronunciation: 'doh',
        languageId: 'hindi',
        category: 'Numbers',
        exampleSentence: 'मेरे पास दो किताबें हैं।',
        exampleTranslation: 'I have two books.',
        difficulty: 1,
      ),
      WordModel(
        id: 'h007',
        word: 'तीन',
        translation: 'Three',
        transliteration: 'Teen',
        pronunciation: 'teen',
        languageId: 'hindi',
        category: 'Numbers',
        exampleSentence: 'तीन बजे मिलते हैं।',
        exampleTranslation: 'Meet at three o\'clock.',
        difficulty: 1,
      ),
      // Colors
      WordModel(
        id: 'h008',
        word: 'लाल',
        translation: 'Red',
        transliteration: 'Laal',
        pronunciation: 'laal',
        languageId: 'hindi',
        category: 'Colors',
        exampleSentence: 'यह फूल लाल है।',
        exampleTranslation: 'This flower is red.',
        difficulty: 1,
      ),
      WordModel(
        id: 'h009',
        word: 'नीला',
        translation: 'Blue',
        transliteration: 'Neela',
        pronunciation: 'nee-la',
        languageId: 'hindi',
        category: 'Colors',
        exampleSentence: 'आसमान नीला है।',
        exampleTranslation: 'The sky is blue.',
        difficulty: 1,
      ),
      WordModel(
        id: 'h010',
        word: 'हरा',
        translation: 'Green',
        transliteration: 'Hara',
        pronunciation: 'ha-ra',
        languageId: 'hindi',
        category: 'Colors',
        exampleSentence: 'घास हरी है।',
        exampleTranslation: 'The grass is green.',
        difficulty: 1,
      ),
      // Food
      WordModel(
        id: 'h011',
        word: 'रोटी',
        translation: 'Bread / Flatbread',
        transliteration: 'Roti',
        pronunciation: 'ro-tee',
        languageId: 'hindi',
        category: 'Food',
        exampleSentence: 'मुझे रोटी और सब्ज़ी पसंद है।',
        exampleTranslation: 'I like bread and vegetables.',
        difficulty: 1,
      ),
      WordModel(
        id: 'h012',
        word: 'पानी',
        translation: 'Water',
        transliteration: 'Paani',
        pronunciation: 'paa-nee',
        languageId: 'hindi',
        category: 'Food',
        exampleSentence: 'मुझे पानी चाहिए।',
        exampleTranslation: 'I need water.',
        difficulty: 1,
      ),
      WordModel(
        id: 'h013',
        word: 'दूध',
        translation: 'Milk',
        transliteration: 'Doodh',
        pronunciation: 'doodh',
        languageId: 'hindi',
        category: 'Food',
        exampleSentence: 'बच्चे को दूध दो।',
        exampleTranslation: 'Give milk to the child.',
        difficulty: 1,
      ),
      // Family
      WordModel(
        id: 'h014',
        word: 'माँ',
        translation: 'Mother',
        transliteration: 'Maa',
        pronunciation: 'maa',
        languageId: 'hindi',
        category: 'Family',
        exampleSentence: 'मेरी माँ बहुत अच्छी हैं।',
        exampleTranslation: 'My mother is very kind.',
        difficulty: 1,
      ),
      WordModel(
        id: 'h015',
        word: 'पिता',
        translation: 'Father',
        transliteration: 'Pita',
        pronunciation: 'pi-taa',
        languageId: 'hindi',
        category: 'Family',
        exampleSentence: 'मेरे पिता डॉक्टर हैं।',
        exampleTranslation: 'My father is a doctor.',
        difficulty: 1,
      ),
      // Grammar
      WordModel(
        id: 'h016',
        word: 'मैं',
        translation: 'I / Me',
        transliteration: 'Main',
        pronunciation: 'main',
        languageId: 'hindi',
        category: 'Grammar',
        exampleSentence: 'मैं भारत में रहता हूँ।',
        exampleTranslation: 'I live in India.',
        difficulty: 1,
      ),
      WordModel(
        id: 'h017',
        word: 'तुम',
        translation: 'You (informal)',
        transliteration: 'Tum',
        pronunciation: 'tum',
        languageId: 'hindi',
        category: 'Grammar',
        exampleSentence: 'तुम कहाँ जा रहे हो?',
        exampleTranslation: 'Where are you going?',
        difficulty: 1,
      ),
      WordModel(
        id: 'h018',
        word: 'वह',
        translation: 'He / She / That',
        transliteration: 'Woh',
        pronunciation: 'voh',
        languageId: 'hindi',
        category: 'Grammar',
        exampleSentence: 'वह स्कूल जाती है।',
        exampleTranslation: 'She goes to school.',
        difficulty: 2,
      ),
      // Travel
      WordModel(
        id: 'h019',
        word: 'बाज़ार',
        translation: 'Market / Bazaar',
        transliteration: 'Bazaar',
        pronunciation: 'baa-zaar',
        languageId: 'hindi',
        category: 'Travel',
        exampleSentence: 'मैं बाज़ार जा रहा हूँ।',
        exampleTranslation: 'I am going to the market.',
        difficulty: 1,
      ),
      WordModel(
        id: 'h020',
        word: 'रेलगाड़ी',
        translation: 'Train',
        transliteration: 'Relgaadi',
        pronunciation: 'rail-gaa-dee',
        languageId: 'hindi',
        category: 'Travel',
        exampleSentence: 'रेलगाड़ी कब आएगी?',
        exampleTranslation: 'When will the train arrive?',
        difficulty: 2,
      ),
    ];
  }

  static List<WordModel> getGujaratiWords() {
    return [
      WordModel(
        id: 'g001',
        word: 'નમસ્તે',
        translation: 'Hello / Greetings',
        transliteration: 'Namaste',
        pronunciation: 'nuh-muh-stay',
        languageId: 'gujarati',
        category: 'Vocabulary',
        exampleSentence: 'નમસ્તે, તમે કેમ છો?',
        exampleTranslation: 'Hello, how are you?',
        difficulty: 1,
      ),
      WordModel(
        id: 'g002',
        word: 'આભાર',
        translation: 'Thank you',
        transliteration: 'Aabhar',
        pronunciation: 'aa-bhaar',
        languageId: 'gujarati',
        category: 'Vocabulary',
        exampleSentence: 'તમારી મદદ માટે આભાર.',
        exampleTranslation: 'Thank you for your help.',
        difficulty: 1,
      ),
      WordModel(
        id: 'g003',
        word: 'ઘર',
        translation: 'Home / House',
        transliteration: 'Ghar',
        pronunciation: 'ghur',
        languageId: 'gujarati',
        category: 'Vocabulary',
        exampleSentence: 'મારું ઘર સુંદર છે.',
        exampleTranslation: 'My house is beautiful.',
        difficulty: 1,
      ),
      WordModel(
        id: 'g004',
        word: 'પાણી',
        translation: 'Water',
        transliteration: 'Paani',
        pronunciation: 'paa-nee',
        languageId: 'gujarati',
        category: 'Food',
        exampleSentence: 'મને પાણી આપો.',
        exampleTranslation: 'Give me water.',
        difficulty: 1,
      ),
      WordModel(
        id: 'g005',
        word: 'એક',
        translation: 'One',
        transliteration: 'Ek',
        pronunciation: 'ek',
        languageId: 'gujarati',
        category: 'Numbers',
        exampleSentence: 'મને એક ચા આપો.',
        exampleTranslation: 'Give me one tea.',
        difficulty: 1,
      ),
      WordModel(
        id: 'g006',
        word: 'બે',
        translation: 'Two',
        transliteration: 'Be',
        pronunciation: 'beh',
        languageId: 'gujarati',
        category: 'Numbers',
        exampleSentence: 'મારા બે ભાઈ છે.',
        exampleTranslation: 'I have two brothers.',
        difficulty: 1,
      ),
      WordModel(
        id: 'g007',
        word: 'લાલ',
        translation: 'Red',
        transliteration: 'Laal',
        pronunciation: 'laal',
        languageId: 'gujarati',
        category: 'Colors',
        exampleSentence: 'આ ફૂલ લાલ છે.',
        exampleTranslation: 'This flower is red.',
        difficulty: 1,
      ),
      WordModel(
        id: 'g008',
        word: 'માં',
        translation: 'Mother',
        transliteration: 'Maa',
        pronunciation: 'maa',
        languageId: 'gujarati',
        category: 'Family',
        exampleSentence: 'મારી માં ખૂબ સારી છે.',
        exampleTranslation: 'My mother is very good.',
        difficulty: 1,
      ),
    ];
  }

  static List<QuizQuestion> getQuizQuestions(String languageId, String category) {
    if (languageId == 'hindi') {
      return [
        QuizQuestion(
          id: 'q001',
          question: 'What does "नमस्ते" mean?',
          options: ['Goodbye', 'Hello / Greetings', 'Thank you', 'Please'],
          correctIndex: 1,
          languageId: languageId,
          category: category,
          type: QuizType.multipleChoice,
        ),
        QuizQuestion(
          id: 'q002',
          question: 'How do you say "Thank you" in Hindi?',
          options: ['कृपया', 'माफ़ करना', 'धन्यवाद', 'नमस्ते'],
          correctIndex: 2,
          languageId: languageId,
          category: category,
          type: QuizType.multipleChoice,
        ),
        QuizQuestion(
          id: 'q003',
          question: 'What does "पानी" mean?',
          options: ['Milk', 'Bread', 'Water', 'Food'],
          correctIndex: 2,
          languageId: languageId,
          category: category,
          type: QuizType.multipleChoice,
        ),
        QuizQuestion(
          id: 'q004',
          question: 'What is "Red" in Hindi?',
          options: ['नीला', 'हरा', 'पीला', 'लाल'],
          correctIndex: 3,
          languageId: languageId,
          category: category,
          type: QuizType.multipleChoice,
        ),
        QuizQuestion(
          id: 'q005',
          question: '"माँ" means Mother. True or False?',
          options: ['True', 'False'],
          correctIndex: 0,
          languageId: languageId,
          category: category,
          type: QuizType.trueFalse,
        ),
        QuizQuestion(
          id: 'q006',
          question: 'What does "तीन" mean?',
          options: ['One', 'Two', 'Three', 'Four'],
          correctIndex: 2,
          languageId: languageId,
          category: category,
          type: QuizType.multipleChoice,
        ),
        QuizQuestion(
          id: 'q007',
          question: 'How do you say "Train" in Hindi?',
          options: ['बाज़ार', 'रेलगाड़ी', 'घर', 'स्कूल'],
          correctIndex: 1,
          languageId: languageId,
          category: category,
          type: QuizType.multipleChoice,
        ),
        QuizQuestion(
          id: 'q008',
          question: 'What does "नीला" mean?',
          options: ['Green', 'Red', 'Yellow', 'Blue'],
          correctIndex: 3,
          languageId: languageId,
          category: category,
          type: QuizType.multipleChoice,
        ),
        QuizQuestion(
          id: 'q009',
          question: 'What is "I / Me" in Hindi?',
          options: ['तुम', 'वह', 'मैं', 'हम'],
          correctIndex: 2,
          languageId: languageId,
          category: category,
          type: QuizType.multipleChoice,
        ),
        QuizQuestion(
          id: 'q010',
          question: '"रोटी" means Water. True or False?',
          options: ['True', 'False'],
          correctIndex: 1,
          languageId: languageId,
          category: category,
          type: QuizType.trueFalse,
        ),
      ];
    }
    return [];
  }

  static List<Achievement> achievements = [
    const Achievement(
      id: 'first_word',
      title: 'First Word!',
      description: 'Learned your first word',
      icon: '🌱',
      xpReward: 10,
      isUnlocked: false,
    ),
    const Achievement(
      id: 'ten_words',
      title: 'Word Collector',
      description: 'Learned 10 words',
      icon: '📚',
      xpReward: 50,
      isUnlocked: false,
    ),
    const Achievement(
      id: 'first_quiz',
      title: 'Quiz Taker',
      description: 'Completed your first quiz',
      icon: '✅',
      xpReward: 25,
      isUnlocked: false,
    ),
    const Achievement(
      id: 'perfect_score',
      title: 'Perfectionist',
      description: 'Got 100% in a quiz',
      icon: '🏆',
      xpReward: 100,
      isUnlocked: false,
    ),
    const Achievement(
      id: 'streak_3',
      title: '3 Day Streak',
      description: 'Studied for 3 days in a row',
      icon: '🔥',
      xpReward: 75,
      isUnlocked: false,
    ),
    const Achievement(
      id: 'streak_7',
      title: 'Week Champion',
      description: 'Studied for 7 days in a row',
      icon: '⚡',
      xpReward: 200,
      isUnlocked: false,
    ),
  ];
}